package ca.bc.gov.mof.lexis.dto.application;

import java.time.LocalDate;
import java.util.List;

public record LexisApplicationDetailDto(
    long applicationNumber,
    String exemptionNumber,
    String applicationStatusCode,
    String statusDescription,
    String ownerClientNumber,
    String agentClientNumber,
    Long orgUnitNumber,
    String orgUnitName,
    String productTypeCode,
    String exemptionReasonCode,
    LocalDate applicationDate,
    LocalDate receivedDate,
    LocalDate listingDate,
    LocalDate teacMeetingDate,
    Long termDays,
    double applicationVolume,
    double averageLogVolume,
    boolean canCreateOffers,
    boolean industryUser,
    boolean readOnly,
    boolean exemptionApprover,
    boolean canEditApplicationDetails,
    boolean canEditPackages,
    boolean canAddPackages,
    boolean canAddScales,
    boolean canUpdatePackageNumber,
    boolean locked,
    String lockedBy,
    String lockMessage,
    List<LexisPackageDto> packages,
    List<LexisRemarkDto> remarks,
    List<LexisOfferDto> offers,
    String jurisdictionCode,
    String author) {

  public LexisApplicationDetailDto(
      long applicationNumber,
      String exemptionNumber,
      String applicationStatusCode,
      String statusDescription,
      String ownerClientNumber,
      String agentClientNumber,
      Long orgUnitNumber,
      String orgUnitName,
      String productTypeCode,
      String exemptionReasonCode,
      LocalDate applicationDate,
      LocalDate receivedDate,
      LocalDate listingDate,
      LocalDate teacMeetingDate,
      Long termDays,
      double applicationVolume,
      double averageLogVolume,
      boolean canCreateOffers,
      boolean industryUser,
      boolean readOnly,
      boolean exemptionApprover,
      boolean canEditApplicationDetails,
      boolean canEditPackages,
      boolean canAddPackages,
      boolean canAddScales,
      boolean canUpdatePackageNumber,
      boolean locked,
      String lockedBy,
      String lockMessage,
      List<LexisPackageDto> packages,
      List<LexisRemarkDto> remarks,
      List<LexisOfferDto> offers,
      String jurisdictionCode) {
    this(
        applicationNumber,
        exemptionNumber,
        applicationStatusCode,
        statusDescription,
        ownerClientNumber,
        agentClientNumber,
        orgUnitNumber,
        orgUnitName,
        productTypeCode,
        exemptionReasonCode,
        applicationDate,
        receivedDate,
        listingDate,
        teacMeetingDate,
        termDays,
        applicationVolume,
        averageLogVolume,
        canCreateOffers,
        industryUser,
        readOnly,
        exemptionApprover,
        canEditApplicationDetails,
        canEditPackages,
        canAddPackages,
        canAddScales,
        canUpdatePackageNumber,
        locked,
        lockedBy,
        lockMessage,
        packages,
        remarks,
        offers,
        jurisdictionCode,
        null);
  }

  public LexisApplicationDetailDto(
      long applicationNumber,
      String exemptionNumber,
      String applicationStatusCode,
      String statusDescription,
      String ownerClientNumber,
      String agentClientNumber,
      Long orgUnitNumber,
      String orgUnitName,
      String productTypeCode,
      String exemptionReasonCode,
      LocalDate applicationDate,
      LocalDate receivedDate,
      LocalDate listingDate,
      LocalDate teacMeetingDate,
      Long termDays,
      double applicationVolume,
      double averageLogVolume,
      boolean canCreateOffers,
      boolean industryUser,
      boolean readOnly,
      boolean exemptionApprover,
      boolean locked,
      String lockedBy,
      String lockMessage,
      List<LexisPackageDto> packages,
      List<LexisRemarkDto> remarks,
      List<LexisOfferDto> offers) {
    this(
        applicationNumber,
        exemptionNumber,
        applicationStatusCode,
        statusDescription,
        ownerClientNumber,
        agentClientNumber,
        orgUnitNumber,
        orgUnitName,
        productTypeCode,
        exemptionReasonCode,
        applicationDate,
        receivedDate,
        listingDate,
        teacMeetingDate,
        termDays,
        applicationVolume,
        averageLogVolume,
        canCreateOffers,
        industryUser,
        readOnly,
        exemptionApprover,
        locked,
        lockedBy,
        lockMessage,
        packages,
        remarks,
        offers,
        null);
  }

  public LexisApplicationDetailDto(
      long applicationNumber,
      String exemptionNumber,
      String applicationStatusCode,
      String statusDescription,
      String ownerClientNumber,
      String agentClientNumber,
      Long orgUnitNumber,
      String orgUnitName,
      String productTypeCode,
      String exemptionReasonCode,
      LocalDate applicationDate,
      LocalDate receivedDate,
      LocalDate listingDate,
      LocalDate teacMeetingDate,
      Long termDays,
      double applicationVolume,
      double averageLogVolume,
      boolean canCreateOffers,
      boolean industryUser,
      boolean readOnly,
      boolean exemptionApprover,
      boolean locked,
      String lockedBy,
      String lockMessage,
      List<LexisPackageDto> packages,
      List<LexisRemarkDto> remarks,
      List<LexisOfferDto> offers,
      String author) {
    this(
        applicationNumber,
        exemptionNumber,
        applicationStatusCode,
        statusDescription,
        ownerClientNumber,
        agentClientNumber,
        orgUnitNumber,
        orgUnitName,
        productTypeCode,
        exemptionReasonCode,
        applicationDate,
        receivedDate,
        listingDate,
        teacMeetingDate,
        termDays,
        applicationVolume,
        averageLogVolume,
        canCreateOffers,
        industryUser,
        readOnly,
        exemptionApprover,
        false,
        false,
        false,
        false,
        false,
        locked,
        lockedBy,
        lockMessage,
        packages,
        remarks,
        offers,
        "P",
        author);
  }

  public record LexisPackageDto(String packageNumber, double volume, long pieceCount) {}

  public record LexisRemarkDto(
      Long remarkId, String title, String remark, String user, LocalDate date) {}

  public record LexisOfferDto(
      String offerNumber, String companyName, LocalDate receivedDate, boolean validOffer, LocalDate withdrawalDate) {}
}
