package ca.bc.gov.mof.lexis.dto.permit.rpc;

public record PermitMutationRequestDto(
    String permitNumber,
    String permitStatus,
    String permitSubmitDate,
    String permitIssueDate,
    String permitExpiryDate,
    String permitRequestDate,
    String exemptionNumber,
    String destinationCompanyName,
    String destinationCountry,
    String transportType,
    String transportName,
    String estimatedShippingDate,
    String portOfExport,
    String otherPortOfExport,
    String permitReceiptNo,
    String permitRemarks,
    String permitGrowthType,
    String permitTotalVolume,
    String permitNumberOfPieces,
    String orgUnitNumber,
    String ownerClientNumber,
    String ownerClientLocation,
    String agentClientNumber,
    String agentClientLocation,
    String oicApplicationNumber,
    String oicRegion,
    String oicPermitTotalPieces,
    String oicPermitTotalVolume,
    String packageAgeClass,
    String packageProductType,
    String overrideInd,
    String overrideFee,
    String overrideComment) {}
