package ca.bc.gov.mof.lexis.repository.exemption;

/** Shared exemption detail projection for the application and approved-exemption report. */
public final class ExemptionDetailQueries {

  // Aggregate assigned scales before joining descriptive application/region rows. The legacy
  // detail procedure sums after those joins, multiplying consumption for multi-region exemptions.
  public static final String BY_NUMBER =
      """
      WITH TARGET_EXEMPTION AS (
        SELECT *
        FROM THE.EXPORT_EXEMPTION
        WHERE EXEMPTION_NUMBER = ?
      ), ASSIGNED_SCALE_VOLUME AS (
        SELECT COALESCE(SUM(ESD.SPECIES_GRADE_VOLUME), 0) AS USED_VOLUME
        FROM TARGET_EXEMPTION EE
        INNER JOIN THE.EXPORT_EXEMPTION_APPLICATION EEA
          ON EEA.EXEMPTION_NUMBER = EE.EXEMPTION_NUMBER
        INNER JOIN THE.EXPORT_PACKAGE EP
          ON EP.APPLICATION_NUMBER = EEA.APPLICATION_NUMBER
        INNER JOIN THE.EXPORT_SCALE_DETAIL ESD
          ON ESD.PACKAGE_NUMBER = EP.PACKAGE_NUMBER
        WHERE ESD.EXPORT_PERMIT_DETAIL_NUMBER IS NOT NULL
      ), EXEMPTION_REGIONS AS (
        SELECT EXEMPTION_NUMBER,
               LISTAGG(ORG_UNIT_NO, ',') WITHIN GROUP (ORDER BY ORG_UNIT_NO) AS ORG_UNIT_NAME
        FROM (
          SELECT EEA.EXEMPTION_NUMBER, OU.ORG_UNIT_NO
          FROM TARGET_EXEMPTION EE
          INNER JOIN THE.EXPORT_EXEMPTION_APPLICATION EEA
            ON EEA.EXEMPTION_NUMBER = EE.EXEMPTION_NUMBER
          INNER JOIN THE.ORG_UNIT OU ON OU.ORG_UNIT_NO = EEA.ORG_UNIT_NO
          UNION
          SELECT OEO.EXEMPTION_NUMBER, OU.ORG_UNIT_NO
          FROM TARGET_EXEMPTION EE
          INNER JOIN THE.OIC_EXEMPTION_ORG_UNIT OEO
            ON OEO.EXEMPTION_NUMBER = EE.EXEMPTION_NUMBER
          INNER JOIN THE.ORG_UNIT OU ON OU.ORG_UNIT_NO = OEO.ORG_UNIT_NO
        )
        GROUP BY EXEMPTION_NUMBER
      )
      SELECT DISTINCT EE.EXEMPTION_NUMBER,
             EE.APPROVED_VOLUME,
             EE.APPROVAL_DATE,
             EE.EXPIRY_DATE,
             EE.OTHER_CONDITIONS,
             EE.ENTRY_USERID,
             EE.ENTRY_TIMESTAMP,
             EE.UPDATE_USERID,
             EE.UPDATE_TIMESTAMP,
             EE.EXPORT_EXEMPTION_TYPE_CODE,
             EE.EXPORT_EXEMPTION_STATUS_CODE,
             EESC.DESCRIPTION AS STATUS_DESCRIPTION,
             EE.APPROVED_VOLUME - SV.USED_VOLUME AS VOLUME_REMAINING,
             ES.ADVERTISING_DATE,
             EO.ORG_UNIT_NAME,
             CASE WHEN EE.EXPORT_EXEMPTION_TYPE_CODE = 'M'
               THEN EEA.AGENT_CLIENT_NUMBER ELSE '' END AS AGENT_CLIENT_NUMBER,
             CASE WHEN EE.EXPORT_EXEMPTION_TYPE_CODE = 'M'
               THEN EEA.OWNER_CLIENT_NUMBER ELSE '' END AS OWNER_CLIENT_NUMBER
      FROM TARGET_EXEMPTION EE
      CROSS JOIN ASSIGNED_SCALE_VOLUME SV
      INNER JOIN THE.EXPORT_EXEMPTION_STATUS_CODE EESC
        ON EESC.EXPORT_EXEMPTION_STATUS_CODE = EE.EXPORT_EXEMPTION_STATUS_CODE
      LEFT JOIN THE.EXPORT_EXEMPTION_APPLICATION EEA
        ON EEA.EXEMPTION_NUMBER = EE.EXEMPTION_NUMBER
      LEFT JOIN THE.EXPORT_SCHEDULE ES ON ES.EXPORT_SCHEDULE_ID = EEA.EXPORT_SCHEDULE_ID
      LEFT JOIN EXEMPTION_REGIONS EO ON EO.EXEMPTION_NUMBER = EE.EXEMPTION_NUMBER
      """;

  private ExemptionDetailQueries() {}
}
