package ca.bc.gov.mof.lexis.dto.exemption;

import java.time.LocalDate;
import java.util.List;

public record ExemptionSearchCriteria(
    String applicationNumber,
    String packageNumber,
    String exemptionNumber,
    String exemptionType,
    String exemptionStatus,
    String applicantClientNumber,
    String ownerClientNumber,
    LocalDate approvalFromDate,
    LocalDate approvalToDate,
    LocalDate listingFromDate,
    LocalDate listingToDate,
    List<Long> regionNumbers,
    boolean includeBlanketOic,
    boolean excludeBlanketOic,
    boolean broadClientMatch,
    String sortField,
    int page,
    int size) {

  public ExemptionSearchCriteria(
      String applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String exemptionType,
      String exemptionStatus,
      String applicantClientNumber,
      String ownerClientNumber,
      LocalDate approvalFromDate,
      LocalDate approvalToDate,
      LocalDate listingFromDate,
      LocalDate listingToDate,
      List<Long> regionNumbers,
      boolean includeBlanketOic,
      boolean excludeBlanketOic,
      String sortField,
      int page,
      int size) {
    this(
        applicationNumber,
        packageNumber,
        exemptionNumber,
        exemptionType,
        exemptionStatus,
        applicantClientNumber,
        ownerClientNumber,
        approvalFromDate,
        approvalToDate,
        listingFromDate,
        listingToDate,
        regionNumbers,
        includeBlanketOic,
        excludeBlanketOic,
        false,
        sortField,
        page,
        size);
  }

  public ExemptionSearchCriteria(
      String applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String exemptionType,
      String exemptionStatus,
      String applicantClientNumber,
      String ownerClientNumber,
      LocalDate approvalFromDate,
      LocalDate approvalToDate,
      LocalDate listingFromDate,
      LocalDate listingToDate,
      List<Long> regionNumbers,
      boolean includeBlanketOic,
      boolean excludeBlanketOic,
      int page,
      int size) {
    this(
        applicationNumber,
        packageNumber,
        exemptionNumber,
        exemptionType,
        exemptionStatus,
        applicantClientNumber,
        ownerClientNumber,
        approvalFromDate,
        approvalToDate,
        listingFromDate,
        listingToDate,
        regionNumbers,
        includeBlanketOic,
        excludeBlanketOic,
        false,
        null,
        page,
        size);
  }

  public ExemptionSearchCriteria(
      String applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String exemptionType,
      String exemptionStatus,
      String applicantClientNumber,
      String ownerClientNumber,
      LocalDate approvalFromDate,
      LocalDate approvalToDate,
      LocalDate listingFromDate,
      LocalDate listingToDate,
      List<Long> regionNumbers,
      boolean includeBlanketOic,
      int page,
      int size) {
    this(
        applicationNumber,
        packageNumber,
        exemptionNumber,
        exemptionType,
        exemptionStatus,
        applicantClientNumber,
        ownerClientNumber,
        approvalFromDate,
        approvalToDate,
        listingFromDate,
        listingToDate,
        regionNumbers,
        includeBlanketOic,
        false,
        false,
        null,
        page,
        size);
  }

  public ExemptionSearchCriteria(
      String applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String exemptionType,
      String exemptionStatus,
      String applicantClientNumber,
      String ownerClientNumber,
      LocalDate approvalFromDate,
      LocalDate approvalToDate,
      LocalDate listingFromDate,
      LocalDate listingToDate,
      List<Long> regionNumbers,
      int page,
      int size) {
    this(
        applicationNumber,
        packageNumber,
        exemptionNumber,
        exemptionType,
        exemptionStatus,
        applicantClientNumber,
        ownerClientNumber,
        approvalFromDate,
        approvalToDate,
        listingFromDate,
        listingToDate,
        regionNumbers,
        false,
        false,
        false,
        null,
        page,
        size);
  }
}
