package ca.bc.gov.mof.lexis.repository.reference;

/** Direct equivalents of selected LEXIS reference reads. */
public final class LexisCodeQueries {

  // Attachment types deliberately include historical codes and have no defined row order.
  public static final String ATTACHMENT_TYPES =
      """
      SELECT C.EXPORT_ATTACHMENT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             NULL AS ORDER_BY,
             NULL AS GROUP_BY
      FROM THE.EXPORT_ATTACHMENT_TYPE_CODE C
      """;

  public static final String ATTACHMENT_TYPE_BY_CODE =
      ATTACHMENT_TYPES + " WHERE C.EXPORT_ATTACHMENT_TYPE_CODE = ?";

  public static final String ACTIVE_TRANSPORT_TYPES =
      """
      SELECT C.EXPORT_TRANSPORT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_TRANSPORT_TYPE_CODE C
      INNER JOIN THE.EXPORT_TRNSPRT_TYPE_CODE_ORDER O
        ON O.EXPORT_TRANSPORT_TYPE_CODE = C.EXPORT_TRANSPORT_TYPE_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_GROWTH_TYPES =
      """
      SELECT C.EXPORT_GROWTH_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_GROWTH_TYPE_CODE C
      INNER JOIN THE.EXPORT_GROWTH_TYPE_CODE_ORDER O
        ON O.EXPORT_GROWTH_TYPE_CODE = C.EXPORT_GROWTH_TYPE_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_PRODUCT_TYPES =
      """
      SELECT C.EXPORT_PRODUCT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PRODUCT_TYPE_CODE C
      INNER JOIN THE.EXPORT_PRODUCT_TYPE_CODE_ORDER O
        ON C.EXPORT_PRODUCT_TYPE_CODE = O.EXPORT_PRODUCT_TYPE_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_COUNTRIES =
      """
      SELECT C.EXPORT_COUNTRY_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_COUNTRY_CODE C
      INNER JOIN THE.EXPORT_COUNTRY_CODE_ORDER O
        ON O.EXPORT_COUNTRY_CODE = C.EXPORT_COUNTRY_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_APPLICATION_STATUSES =
      """
      SELECT C.EXPORT_APPLICATION_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_APPLICATION_STATUS_CODE C
      INNER JOIN THE.EXPORT_APPLN_STS_CODE_ORDER O
        ON C.EXPORT_APPLICATION_STATUS_CODE = O.EXPORT_APPLICATION_STATUS_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_EXEMPTION_TYPES =
      """
      SELECT C.EXPORT_EXEMPTION_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_TYPE_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_TYPE_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_TYPE_CODE = C.EXPORT_EXEMPTION_TYPE_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_EXEMPTION_REASONS =
      """
      SELECT C.EXPORT_EXEMPTION_REASON_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_REASON_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_RSN_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_REASON_CODE = C.EXPORT_EXEMPTION_REASON_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_EXEMPTION_STATUSES =
      """
      SELECT C.EXPORT_EXEMPTION_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_STATUS_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_STS_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_STATUS_CODE = C.EXPORT_EXEMPTION_STATUS_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_JURISDICTIONS =
      """
      SELECT C.EXPORT_JURISDICTION_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_JURISDICTION_CODE C
      INNER JOIN THE.EXPORT_JURISDICTION_CODE_ORDER O
        ON O.EXPORT_JURISDICTION_CODE = C.EXPORT_JURISDICTION_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_PERMIT_STATUSES =
      """
      SELECT C.EXPORT_PERMIT_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PERMIT_STATUS_CODE C
      INNER JOIN THE.EXPORT_PERMIT_STS_CODE_ORDER O
        ON O.EXPORT_PERMIT_STATUS_CODE = C.EXPORT_PERMIT_STATUS_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_SPECIES =
      """
      SELECT C.EXPORT_SPECIES_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_SPECIES_CODE C
      INNER JOIN THE.EXPORT_SPECIES_CODE_ORDER O
        ON O.EXPORT_SPECIES_CODE = C.EXPORT_SPECIES_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_PACKAGE_STATUSES =
      """
      SELECT C.EXPORT_PACKAGE_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PACKAGE_STATUS_CODE C
      INNER JOIN THE.EXPORT_PCKG_STATUS_CODE_ORDER O
        ON O.EXPORT_PACKAGE_STATUS_CODE = C.EXPORT_PACKAGE_STATUS_CODE
      WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String ACTIVE_COUNTRIES_BY_GROUP =
      """
      SELECT C.EXPORT_COUNTRY_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_COUNTRY_CODE C
      INNER JOIN THE.EXPORT_COUNTRY_CODE_ORDER O
        ON C.EXPORT_COUNTRY_CODE = O.EXPORT_COUNTRY_CODE
      WHERE O.GROUP_BY = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.ORDER_BY
      """;

  public static final String APPLICATION_STATUS_BY_CODE =
      """
      SELECT C.EXPORT_APPLICATION_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_APPLICATION_STATUS_CODE C
      INNER JOIN THE.EXPORT_APPLN_STS_CODE_ORDER O
        ON C.EXPORT_APPLICATION_STATUS_CODE = O.EXPORT_APPLICATION_STATUS_CODE
      WHERE C.EXPORT_APPLICATION_STATUS_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      """;

  public static final String EXEMPTION_REASON_BY_CODE =
      """
      SELECT C.EXPORT_EXEMPTION_REASON_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_REASON_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_RSN_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_REASON_CODE = C.EXPORT_EXEMPTION_REASON_CODE
      WHERE C.EXPORT_EXEMPTION_REASON_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String APPLICANT_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_APPLICANT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_APPLICANT_TYPE_CODE C
      INNER JOIN THE.EXPORT_APPLCNT_TYPE_CODE_ORDER O
        ON O.EXPORT_APPLICANT_TYPE_CODE = C.EXPORT_APPLICANT_TYPE_CODE
      WHERE C.EXPORT_APPLICANT_TYPE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String JURISDICTION_BY_CODE =
      """
      SELECT C.EXPORT_JURISDICTION_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_JURISDICTION_CODE C
      INNER JOIN THE.EXPORT_JURISDICTION_CODE_ORDER O
        ON O.EXPORT_JURISDICTION_CODE = C.EXPORT_JURISDICTION_CODE
      WHERE C.EXPORT_JURISDICTION_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String EXEMPTION_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_EXEMPTION_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_TYPE_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_TYPE_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_TYPE_CODE = C.EXPORT_EXEMPTION_TYPE_CODE
      WHERE C.EXPORT_EXEMPTION_TYPE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String EXEMPTION_STATUS_BY_CODE =
      """
      SELECT C.EXPORT_EXEMPTION_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_EXEMPTION_STATUS_CODE C
      INNER JOIN THE.EXPORT_EXEMPT_STS_CODE_ORDER O
        ON O.EXPORT_EXEMPTION_STATUS_CODE = C.EXPORT_EXEMPTION_STATUS_CODE
      WHERE C.EXPORT_EXEMPTION_STATUS_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  // File-type lookup deliberately accepts historical codes.
  public static final String FILE_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_FILE_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             NULL AS ORDER_BY,
             NULL AS GROUP_BY
      FROM THE.EXPORT_FILE_TYPE_CODE C
      WHERE C.EXPORT_FILE_TYPE_CODE = ?
      """;

  public static final String COUNTRY_BY_CODE =
      """
      SELECT C.EXPORT_COUNTRY_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_COUNTRY_CODE C
      INNER JOIN THE.EXPORT_COUNTRY_CODE_ORDER O
        ON O.EXPORT_COUNTRY_CODE = C.EXPORT_COUNTRY_CODE
      WHERE C.EXPORT_COUNTRY_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String TRANSPORT_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_TRANSPORT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_TRANSPORT_TYPE_CODE C
      INNER JOIN THE.EXPORT_TRNSPRT_TYPE_CODE_ORDER O
        ON O.EXPORT_TRANSPORT_TYPE_CODE = C.EXPORT_TRANSPORT_TYPE_CODE
      WHERE C.EXPORT_TRANSPORT_TYPE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String PERMIT_STATUS_BY_CODE =
      """
      SELECT C.EXPORT_PERMIT_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PERMIT_STATUS_CODE C
      INNER JOIN THE.EXPORT_PERMIT_STS_CODE_ORDER O
        ON O.EXPORT_PERMIT_STATUS_CODE = C.EXPORT_PERMIT_STATUS_CODE
      WHERE C.EXPORT_PERMIT_STATUS_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String SCALE_METHOD_BY_CODE =
      """
      SELECT C.EXPORT_SCALE_METHOD_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_SCALE_METHOD_CODE C
      INNER JOIN THE.EXPORT_SCALE_METHOD_CODE_ORDER O
        ON O.EXPORT_SCALE_METHOD_CODE = C.EXPORT_SCALE_METHOD_CODE
      WHERE C.EXPORT_SCALE_METHOD_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String SPECIES_GRADE_END_USES_BY_REGION =
      """
      SELECT SGE.EXPORT_SPECIES_CODE,
             SGE.SPECIES_GRADE_ENDUSE_REGION_ID,
             SGE.EXCOL_TRANSLATION_VALUE,
             SGE.EXPORT_END_USE_CODE,
             SGE.ORG_UNIT_NO,
             SGE.EXPORT_GRADE_CODE
      FROM THE.SPECIES_GRADE_ENDUSE_RGN_XREF SGE
      WHERE SGE.ORG_UNIT_NO = ?
      """;

  public static final String SPECIES_GRADE_END_USES_BY_REGION_SPECIES =
      SPECIES_GRADE_END_USES_BY_REGION + " AND SGE.EXPORT_SPECIES_CODE = ?";

  public static final String SPECIES_BY_CODE =
      """
      SELECT C.EXPORT_SPECIES_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_SPECIES_CODE C
      INNER JOIN THE.EXPORT_SPECIES_CODE_ORDER O
        ON O.EXPORT_SPECIES_CODE = C.EXPORT_SPECIES_CODE
      WHERE C.EXPORT_SPECIES_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String GRADE_BY_CODE =
      """
      SELECT C.EXPORT_GRADE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_GRADE_CODE C
      INNER JOIN THE.EXPORT_GRADE_CODE_ORDER O
        ON O.EXPORT_GRADE_CODE = C.EXPORT_GRADE_CODE
      WHERE C.EXPORT_GRADE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String END_USE_BY_CODE =
      """
      SELECT C.EXPORT_END_USE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_END_USE_CODE C
      INNER JOIN THE.EXPORT_END_USE_CODE_ORDER O
        ON O.EXPORT_END_USE_CODE = C.EXPORT_END_USE_CODE
      WHERE C.EXPORT_END_USE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  public static final String GROWTH_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_GROWTH_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_GROWTH_TYPE_CODE C
      INNER JOIN THE.EXPORT_GROWTH_TYPE_CODE_ORDER O
        ON O.EXPORT_GROWTH_TYPE_CODE = C.EXPORT_GROWTH_TYPE_CODE
      WHERE C.EXPORT_GROWTH_TYPE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  // Unlike the product list, FIND_PRODUCT_TYPE_CODE has no defined row order.
  public static final String PRODUCT_TYPE_BY_CODE =
      """
      SELECT C.EXPORT_PRODUCT_TYPE_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PRODUCT_TYPE_CODE C
      INNER JOIN THE.EXPORT_PRODUCT_TYPE_CODE_ORDER O
        ON C.EXPORT_PRODUCT_TYPE_CODE = O.EXPORT_PRODUCT_TYPE_CODE
      WHERE C.EXPORT_PRODUCT_TYPE_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      """;

  public static final String PACKAGE_STATUS_BY_CODE =
      """
      SELECT C.EXPORT_PACKAGE_STATUS_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             O.ORDER_BY,
             O.GROUP_BY
      FROM THE.EXPORT_PACKAGE_STATUS_CODE C
      INNER JOIN THE.EXPORT_PCKG_STATUS_CODE_ORDER O
        ON O.EXPORT_PACKAGE_STATUS_CODE = C.EXPORT_PACKAGE_STATUS_CODE
      WHERE C.EXPORT_PACKAGE_STATUS_CODE = ?
        AND SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE
      ORDER BY O.GROUP_BY, O.ORDER_BY
      """;

  private static final String ORG_UNIT_SELECT =
      """
      SELECT O.ORG_UNIT_NO,
             O.ORG_UNIT_CODE,
             O.ORG_UNIT_NAME,
             O.LOCATION_CODE,
             O.AREA_CODE,
             O.TELEPHONE_NO,
             O.ORG_LEVEL_CODE,
             O.OFFICE_NAME_CODE,
             O.ROLLUP_REGION_NO,
             O.ROLLUP_REGION_CODE,
             O.ROLLUP_DIST_NO,
             O.ROLLUP_DIST_CODE,
             O.EFFECTIVE_DATE,
             O.EXPIRY_DATE,
             O.UPDATE_TIMESTAMP
      FROM THE.ORG_UNIT O
      """;

  // Both legacy lookups include historical org units and have no date filter.
  public static final String ORG_UNIT_BY_NUMBER = ORG_UNIT_SELECT + " WHERE O.ORG_UNIT_NO = ?";

  public static final String ORG_UNIT_BY_CODE = ORG_UNIT_SELECT + " WHERE O.ORG_UNIT_CODE = ?";

  private static final String PORT_SELECT =
      """
      SELECT C.EXPORT_PORT_OF_EXPORT_CODE AS CODE,
             C.DESCRIPTION,
             C.EFFECTIVE_DATE,
             C.EXPIRY_DATE,
             C.UPDATE_TIMESTAMP,
             NULL AS ORDER_BY,
             NULL AS GROUP_BY
      FROM THE.EXPORT_PORT_OF_EXPORT_CODE C
      """;

  public static final String ACTIVE_PORTS =
      PORT_SELECT + " WHERE SYSDATE BETWEEN C.EFFECTIVE_DATE AND C.EXPIRY_DATE";

  // Unlike the active list, the legacy detail lookup also accepts historical port codes.
  // Preserve FIND_PORT_CODE's equality predicate; it does not normalize case with UPPER.
  public static final String PORT_BY_CODE =
      PORT_SELECT + " WHERE C.EXPORT_PORT_OF_EXPORT_CODE = ?";

  private LexisCodeQueries() {}
}
