LogFile /dev/stdout
LogTime yes
DatabaseDirectory /opt/app-root/src
TCPSocket 3310
StreamMaxLength 25M
ReadTimeout 120
CommandReadTimeout 10
SendBufTimeout 500
MaxThreads 10
MaxQueue 30
Foreground yes
TemporaryDirectory /tmp/clamav
AllowSupplementaryGroups yes
ScanArchive yes
Bytecode yes
