package ca.bc.gov.mof.lexis.dto.permit;

import java.time.LocalDate;

public record PermitDetailDto(
    Long permitNumber,
    Long applicationNumber,
    String packageNumber,
    String exemptionNumber,
    String permitStatusCode,
    String permitStatusDescription,
    String applicantClientNumber,
    String agentClientLocationCode,
    String ownerClientNumber,
    String ownerClientLocationCode,
    String destinationCompanyName,
    String destinationCountryCode,
    String transportTypeCode,
    String transportName,
    String portOfExportCode,
    String otherPortOfExport,
    LocalDate applicationDate,
    LocalDate issueDate,
    LocalDate expiryDate,
    LocalDate receivedDate,
    LocalDate estimatedShippingDate,
    double permitVolume,
    long numberOfPieces,
    String receiptNumber,
    String federalPermitNumber,
    String invoiceNumber,
    String remarks,
    Long oicApplicationNumber,
    Long oicRequestPieces,
    Double oicRequestVolume,
    Long orgUnitNumber,
    String region,
    String author) {

  public PermitDetailDto(
      Long permitNumber,
      Long applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String permitStatusCode,
      String permitStatusDescription,
      String applicantClientNumber,
      String agentClientLocationCode,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String destinationCompanyName,
      String destinationCountryCode,
      String transportTypeCode,
      String transportName,
      String portOfExportCode,
      String otherPortOfExport,
      LocalDate issueDate,
      LocalDate expiryDate,
      LocalDate receivedDate,
      LocalDate estimatedShippingDate,
      double permitVolume,
      long numberOfPieces,
      String receiptNumber,
      String federalPermitNumber,
      String invoiceNumber,
      String remarks,
      Long oicApplicationNumber,
      Long orgUnitNumber,
      String region) {
    this(
        permitNumber,
        applicationNumber,
        packageNumber,
        exemptionNumber,
        permitStatusCode,
        permitStatusDescription,
        applicantClientNumber,
        agentClientLocationCode,
        ownerClientNumber,
        ownerClientLocationCode,
        destinationCompanyName,
        destinationCountryCode,
        transportTypeCode,
        transportName,
        portOfExportCode,
        otherPortOfExport,
        null,
        issueDate,
        expiryDate,
        receivedDate,
        estimatedShippingDate,
        permitVolume,
        numberOfPieces,
        receiptNumber,
        federalPermitNumber,
        invoiceNumber,
        remarks,
        oicApplicationNumber,
        null,
        null,
        orgUnitNumber,
        region,
        null);
  }

  public PermitDetailDto(
      Long permitNumber,
      Long applicationNumber,
      String packageNumber,
      String exemptionNumber,
      String permitStatusCode,
      String permitStatusDescription,
      String applicantClientNumber,
      String agentClientLocationCode,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String destinationCompanyName,
      String destinationCountryCode,
      String transportTypeCode,
      String transportName,
      String portOfExportCode,
      String otherPortOfExport,
      LocalDate issueDate,
      LocalDate expiryDate,
      LocalDate receivedDate,
      LocalDate estimatedShippingDate,
      double permitVolume,
      long numberOfPieces,
      String receiptNumber,
      String federalPermitNumber,
      String invoiceNumber,
      String remarks,
      Long oicApplicationNumber,
      String region) {
    this(
        permitNumber,
        applicationNumber,
        packageNumber,
        exemptionNumber,
        permitStatusCode,
        permitStatusDescription,
        applicantClientNumber,
        agentClientLocationCode,
        ownerClientNumber,
        ownerClientLocationCode,
        destinationCompanyName,
        destinationCountryCode,
        transportTypeCode,
        transportName,
        portOfExportCode,
        otherPortOfExport,
        null,
        issueDate,
        expiryDate,
        receivedDate,
        estimatedShippingDate,
        permitVolume,
        numberOfPieces,
        receiptNumber,
        federalPermitNumber,
        invoiceNumber,
        remarks,
        oicApplicationNumber,
        null,
        null,
        null,
        region,
        null);
  }
}
