package ca.bc.gov.mof.lexis.dto.federal;

import java.time.LocalDate;
import java.util.List;

public record FederalApplicationDetailDto(
    Long applicationNumber,
    String federalApplicationNumber,
    String statusCode,
    String statusDescription,
    String ownerClientNumber,
    String ownerClientLocationCode,
    String agentClientNumber,
    String agentClientLocationCode,
    String exemptionNumber,
    String exemptionType,
    String exemptionReason,
    LocalDate receivedDate,
    LocalDate listingDate,
    boolean readOnly,
    List<String> packages,
    List<String> remarks,
    List<FederalApplicationOfferDto> offers,
    FederalApplicationPermitDto federalPermit,
    String ownerApplicantType,
    String ownerContactName,
    String ownerCompanyName,
    String agentApplicantType,
    String agentContactName,
    String agentCompanyName,
    String region,
    String productType,
    LocalDate applicationDate,
    Long termDays,
    String logLocation,
    String ageClass,
    Double averageLogVolume,
    Double applicationVolume,
    String endUse,
    String author,
    FederalApplicationClientContextDto ownerClientContext,
    FederalApplicationClientContextDto agentClientContext,
    boolean locked,
    boolean lockHeldByCurrentUser,
    String lockedBy,
    String lockMessage,
    // The application's region, so the page can hide region-limited writes.
    Long orgUnitNumber) {

  /** The pre-region shape; the application's region is added separately. */
  public FederalApplicationDetailDto(
      Long applicationNumber,
      String federalApplicationNumber,
      String statusCode,
      String statusDescription,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String agentClientNumber,
      String agentClientLocationCode,
      String exemptionNumber,
      String exemptionType,
      String exemptionReason,
      LocalDate receivedDate,
      LocalDate listingDate,
      boolean readOnly,
      List<String> packages,
      List<String> remarks,
      List<FederalApplicationOfferDto> offers,
      FederalApplicationPermitDto federalPermit,
      String ownerApplicantType,
      String ownerContactName,
      String ownerCompanyName,
      String agentApplicantType,
      String agentContactName,
      String agentCompanyName,
      String region,
      String productType,
      LocalDate applicationDate,
      Long termDays,
      String logLocation,
      String ageClass,
      Double averageLogVolume,
      Double applicationVolume,
      String endUse,
      String author,
      FederalApplicationClientContextDto ownerClientContext,
      FederalApplicationClientContextDto agentClientContext,
      boolean locked,
      boolean lockHeldByCurrentUser,
      String lockedBy,
      String lockMessage) {
    this(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        null);
  }

  public FederalApplicationDetailDto(
      Long applicationNumber,
      String federalApplicationNumber,
      String statusCode,
      String statusDescription,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String agentClientNumber,
      String agentClientLocationCode,
      String exemptionNumber,
      String exemptionType,
      String exemptionReason,
      LocalDate receivedDate,
      LocalDate listingDate,
      boolean readOnly,
      List<String> packages,
      List<String> remarks,
      List<FederalApplicationOfferDto> offers,
      FederalApplicationPermitDto federalPermit,
      String ownerApplicantType,
      String ownerContactName,
      String ownerCompanyName,
      String agentApplicantType,
      String agentContactName,
      String agentCompanyName,
      String region,
      String productType,
      LocalDate applicationDate,
      Long termDays,
      String logLocation,
      String ageClass,
      Double averageLogVolume,
      Double applicationVolume,
      String endUse,
      String author) {
    this(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        null,
        null,
        false,
        false,
        null,
        null);
  }

  public FederalApplicationDetailDto(
      Long applicationNumber,
      String federalApplicationNumber,
      String statusCode,
      String statusDescription,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String agentClientNumber,
      String agentClientLocationCode,
      String exemptionNumber,
      String exemptionType,
      String exemptionReason,
      LocalDate receivedDate,
      LocalDate listingDate,
      boolean readOnly,
      List<String> packages,
      List<String> remarks,
      List<FederalApplicationOfferDto> offers,
      FederalApplicationPermitDto federalPermit) {
    this(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        false,
        false,
        null,
        null);
  }

  public FederalApplicationDetailDto withClientContexts(
      FederalApplicationClientContextDto ownerContext,
      FederalApplicationClientContextDto agentContext) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerContext,
        agentContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        orgUnitNumber);
  }

  public FederalApplicationDetailDto withEndUse(String resolvedEndUse) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        resolvedEndUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        orgUnitNumber);
  }

  public FederalApplicationDetailDto withProductDescriptions(
      String resolvedProductType, String resolvedAgeClass) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        resolvedProductType,
        applicationDate,
        termDays,
        logLocation,
        resolvedAgeClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        orgUnitNumber);
  }

  public FederalApplicationDetailDto withReadOnly(boolean resolvedReadOnly) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        resolvedReadOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        orgUnitNumber);
  }

  public FederalApplicationDetailDto withEditLock(
      boolean locked,
      boolean lockHeldByCurrentUser,
      String lockedBy,
      String lockMessage) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        orgUnitNumber);
  }

  public FederalApplicationDetailDto withOrgUnitNumber(Long resolvedOrgUnitNumber) {
    return new FederalApplicationDetailDto(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        ownerApplicantType,
        ownerContactName,
        ownerCompanyName,
        agentApplicantType,
        agentContactName,
        agentCompanyName,
        region,
        productType,
        applicationDate,
        termDays,
        logLocation,
        ageClass,
        averageLogVolume,
        applicationVolume,
        endUse,
        author,
        ownerClientContext,
        agentClientContext,
        locked,
        lockHeldByCurrentUser,
        lockedBy,
        lockMessage,
        resolvedOrgUnitNumber);
  }
}
