package ca.bc.gov.mof.lexis.dto.federal;

import java.time.LocalDate;
import java.util.List;

public record FederalApplicationDetailDto(
    Long applicationNumber,
    String federalApplicationNumber,
    String statusCode,
    String statusDescription,
    String ownerClientNumber,
    String ownerClientLocationCode,
    String agentClientNumber,
    String agentClientLocationCode,
    String exemptionNumber,
    String exemptionType,
    String exemptionReason,
    LocalDate receivedDate,
    LocalDate listingDate,
    boolean readOnly,
    List<String> packages,
    List<String> remarks,
    List<String> offers,
    FederalApplicationPermitDto federalPermit,
    String ownerApplicantType,
    String ownerContactName,
    String ownerCompanyName,
    String agentApplicantType,
    String agentContactName,
    String agentCompanyName,
    String region,
    String productType,
    LocalDate applicationDate,
    Long termDays,
    String logLocation,
    String ageClass,
    Double averageLogVolume,
    Double applicationVolume,
    String endUse,
    String author) {

  public FederalApplicationDetailDto(
      Long applicationNumber,
      String federalApplicationNumber,
      String statusCode,
      String statusDescription,
      String ownerClientNumber,
      String ownerClientLocationCode,
      String agentClientNumber,
      String agentClientLocationCode,
      String exemptionNumber,
      String exemptionType,
      String exemptionReason,
      LocalDate receivedDate,
      LocalDate listingDate,
      boolean readOnly,
      List<String> packages,
      List<String> remarks,
      List<String> offers,
      FederalApplicationPermitDto federalPermit) {
    this(
        applicationNumber,
        federalApplicationNumber,
        statusCode,
        statusDescription,
        ownerClientNumber,
        ownerClientLocationCode,
        agentClientNumber,
        agentClientLocationCode,
        exemptionNumber,
        exemptionType,
        exemptionReason,
        receivedDate,
        listingDate,
        readOnly,
        packages,
        remarks,
        offers,
        federalPermit,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
  }
}
