package ca.bc.gov.mof.lexis.dto.offer;

import java.time.LocalDate;

public record PurchaseOfferDetailDto(
    Long offerNumber,
    Long applicationNumber,
    String packageNumber,
    Double packageVolume,
    String speciesGradeCode,
    String companyName,
    String contactName,
    double purchaseOfferAmount,
    LocalDate purchaseOfferDate,
    LocalDate offerWithdrawalDate,
    LocalDate teacReviewDate,
    String approvalIndicator,
    String validOfferIndicator,
    String fairOfferIndicator,
    String offerRemark,
    String withdrawReason,
    String exportJurisdictionCode,
    String manufacturingFacilityInfo,
    String offeringClientNumber,
    String pickupLocation,
    String offerCondition,
    LocalDate advertisingDate,
    LocalDate offerEndDate,
    Double offerVolume,
    String region,
    boolean canEditScheduleDates,
    boolean canEditOfferRemarks,
    boolean canEditOfferDetails,
    boolean canEditWithdrawFields,
    boolean locked,
    String lockedBy,
    String lockMessage,
    String author) {

  public PurchaseOfferDetailDto(
      Long offerNumber,
      Long applicationNumber,
      String packageNumber,
      Double packageVolume,
      String speciesGradeCode,
      String companyName,
      String contactName,
      double purchaseOfferAmount,
      LocalDate purchaseOfferDate,
      LocalDate offerWithdrawalDate,
      LocalDate teacReviewDate,
      String approvalIndicator,
      String validOfferIndicator,
      String fairOfferIndicator,
      String offerRemark,
      String withdrawReason,
      String exportJurisdictionCode,
      String manufacturingFacilityInfo,
      String offeringClientNumber,
      String pickupLocation,
      String offerCondition,
      LocalDate advertisingDate,
      LocalDate offerEndDate,
      Double offerVolume,
      String region,
      boolean canEditScheduleDates,
      boolean canEditOfferRemarks,
      boolean canEditOfferDetails,
      boolean canEditWithdrawFields) {
    this(
        offerNumber,
        applicationNumber,
        packageNumber,
        packageVolume,
        speciesGradeCode,
        companyName,
        contactName,
        purchaseOfferAmount,
        purchaseOfferDate,
        offerWithdrawalDate,
        teacReviewDate,
        approvalIndicator,
        validOfferIndicator,
        fairOfferIndicator,
        offerRemark,
        withdrawReason,
        exportJurisdictionCode,
        manufacturingFacilityInfo,
        offeringClientNumber,
        pickupLocation,
        offerCondition,
        advertisingDate,
        offerEndDate,
        offerVolume,
        region,
        canEditScheduleDates,
        canEditOfferRemarks,
        canEditOfferDetails,
        canEditWithdrawFields,
        false,
        null,
        null,
        null);
  }

  public PurchaseOfferDetailDto(
      Long offerNumber,
      Long applicationNumber,
      String packageNumber,
      Double packageVolume,
      String speciesGradeCode,
      String companyName,
      String contactName,
      double purchaseOfferAmount,
      LocalDate purchaseOfferDate,
      LocalDate offerWithdrawalDate,
      LocalDate teacReviewDate,
      String approvalIndicator,
      String validOfferIndicator,
      String fairOfferIndicator,
      String offerRemark,
      String withdrawReason,
      String exportJurisdictionCode,
      String manufacturingFacilityInfo,
      String offeringClientNumber,
      String pickupLocation,
      String offerCondition,
      LocalDate advertisingDate,
      LocalDate offerEndDate,
      Double offerVolume,
      String region) {
    this(
        offerNumber,
        applicationNumber,
        packageNumber,
        packageVolume,
        speciesGradeCode,
        companyName,
        contactName,
        purchaseOfferAmount,
        purchaseOfferDate,
        offerWithdrawalDate,
        teacReviewDate,
        approvalIndicator,
        validOfferIndicator,
        fairOfferIndicator,
        offerRemark,
        withdrawReason,
        exportJurisdictionCode,
        manufacturingFacilityInfo,
        offeringClientNumber,
        pickupLocation,
        offerCondition,
        advertisingDate,
        offerEndDate,
        offerVolume,
        region,
        false,
        false,
        false,
        false,
        false,
        null,
        null,
        null);
  }

  public PurchaseOfferDetailDto withApplicationContext(
      Double packageVolume, String speciesGradeCode) {
    return new PurchaseOfferDetailDto(
        offerNumber,
        applicationNumber,
        packageNumber,
        packageVolume,
        speciesGradeCode,
        companyName,
        contactName,
        purchaseOfferAmount,
        purchaseOfferDate,
        offerWithdrawalDate,
        teacReviewDate,
        approvalIndicator,
        validOfferIndicator,
        fairOfferIndicator,
        offerRemark,
        withdrawReason,
        exportJurisdictionCode,
        manufacturingFacilityInfo,
        offeringClientNumber,
        pickupLocation,
        offerCondition,
        advertisingDate,
        offerEndDate,
        offerVolume,
        region,
        canEditScheduleDates,
        canEditOfferRemarks,
        canEditOfferDetails,
        canEditWithdrawFields,
        locked,
        lockedBy,
        lockMessage,
        author);
  }

  public PurchaseOfferDetailDto withEditPermissions(
      boolean canEditScheduleDates,
      boolean canEditOfferRemarks,
      boolean canEditOfferDetails,
      boolean canEditWithdrawFields) {
    return new PurchaseOfferDetailDto(
        offerNumber,
        applicationNumber,
        packageNumber,
        packageVolume,
        speciesGradeCode,
        companyName,
        contactName,
        purchaseOfferAmount,
        purchaseOfferDate,
        offerWithdrawalDate,
        teacReviewDate,
        approvalIndicator,
        validOfferIndicator,
        fairOfferIndicator,
        canEditOfferRemarks ? offerRemark : null,
        withdrawReason,
        exportJurisdictionCode,
        manufacturingFacilityInfo,
        offeringClientNumber,
        pickupLocation,
        offerCondition,
        advertisingDate,
        offerEndDate,
        offerVolume,
        region,
        canEditScheduleDates,
        canEditOfferRemarks,
        canEditOfferDetails,
        canEditWithdrawFields,
        locked,
        lockedBy,
        lockMessage,
        author);
  }

  public PurchaseOfferDetailDto withEditLock(
      boolean locked, String lockedBy, String lockMessage) {
    return new PurchaseOfferDetailDto(
        offerNumber,
        applicationNumber,
        packageNumber,
        packageVolume,
        speciesGradeCode,
        companyName,
        contactName,
        purchaseOfferAmount,
        purchaseOfferDate,
        offerWithdrawalDate,
        teacReviewDate,
        approvalIndicator,
        validOfferIndicator,
        fairOfferIndicator,
        offerRemark,
        withdrawReason,
        exportJurisdictionCode,
        manufacturingFacilityInfo,
        offeringClientNumber,
        pickupLocation,
        offerCondition,
        advertisingDate,
        offerEndDate,
        offerVolume,
        region,
        canEditScheduleDates,
        canEditOfferRemarks,
        canEditOfferDetails,
        canEditWithdrawFields,
        locked,
        lockedBy,
        lockMessage,
        author);
  }
}
