name: BCeID Regression

on:
  schedule:
    - cron: "0 10 * * 3" # Wednesdays at 10:00 UTC; 3 AM Pacific during daylight time.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  bceid-regression:
    name: TEST BCeID Provincial Submitter
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-bceid-regression.yml
    secrets:
      e2e_bceid_user: ${{ secrets.E2E_BCEID_USER }}
      e2e_bceid_password: ${{ secrets.E2E_BCEID_PASSWORD }}
    with:
      target: test
